-- Tabela dla roślin
CREATE TABLE IF NOT EXISTS plants (
                                      id INTEGER PRIMARY KEY AUTOINCREMENT,
                                      name VARCHAR(255) NOT NULL UNIQUE
);

-- Wstawianie rekordów
INSERT OR IGNORE INTO plants (name) VALUES
                              -- A                              ('Aloe Vera'),
                              ('Apple Tree'),
                              ('Apricot Tree'),
                              ('Ash Tree'),
                              ('Asparagus'),
                              ('Aster'),
                              ('Azalea'),
                              ('African Violet'),
                              ('Amaranth'),
                              ('Angelica'),
                              ('Anemone'),
                              ('Arbutus'),
                              ('Arnica'),
                              ('Arrowhead'),
                              ('Avocado'),
                              ('Acanthus'),
                              ('Amaryllis'),
                              ('Acacia'),
                              ('Allium'),
                              ('Almond Tree'),
                              ('Aubrieta'),
                              ('Atriplex'),
                              ('Azadirachta'),
                              ('Achillea'),
                              ('Aegopodium'),
                              ('Agapanthus'),
                              ('Agave'),
                              ('Ajuga'),
                              ('Albizia'),
                              ('Alchemilla'),
                              ('Alstroemeria'),
                              ('Amelanchier'),
                              ('Amorphophallus'),
                              ('Andromeda'),
                              ('Anthurium'),
                              ('Aralia'),
                              ('Arctostaphylos'),
                              ('Ardisia'),
                              ('Artemisia'),
                              ('Asclepias'),
                              ('Aspidistra'),
                              ('Astragalus'),
                              ('Atriplex canescens'),
                              ('Aubergine'),
                              -- B
                              ('Bamboo'),
                              ('Banana Tree'),
                              ('Basil'),
                              ('Bay Laurel'),
                              ('Bee Balm'),
                              ('Begonia'),
                              ('Bellflower'),
                              ('Bergenia'),
                              ('Birch Tree'),
                              ('Blackberry'),
                              ('Blackcurrant'),
                              ('Blazing Star'),
                              ('Bleeding Heart'),
                              ('Bluebell'),
                              ('Blueberry'),
                              ('Bog Rosemary'),
                              ('Bottlebrush'),
                              ('Bougainvillea'),
                              ('Boxwood'),
                              ('Bramble'),
                              ('Brazil Nut Tree'),
                              ('Bromeliad'),
                              ('Brooklime'),
                              ('Broom'),
                              ('Brown Eyed Susan'),
                              ('Brunnera'),
                              ('Buttercup'),
                              ('Butterfly Bush'),
                              ('Buttonbush'),
                              ('Blue Fescue'),
                              ('Balloon Flower'),
                              ('Bearberry'),
                              ('Beardtongue'),
                              ('Beech Tree'),
                              ('Bittercress'),
                              ('Black Elder'),
                              ('Black Locust'),
                              ('Black-eyed Susan'),
                              ('Bladderwort'),
                              ('Bloodroot'),
                              ('Blue Flax'),
                              ('Blue Grama'),
                              ('Blue Oak'),
                              ('Blue Spruce'),
                              ('Bluntleaf Heath'),
                              ('Bogbean'),
                              ('Bog Laurel'),
                              ('Bottle Gentian'),
                              ('Box Elder'),
                              ('Bracted Spiderwort'),
                              ('Brain Cactus'),
                              ('Brittlebush'),
                              ('Broadleaf Arrowhead'),
                              ('Broadleaf Lupine'),
                              ('Broadleaf Plantain'),
                              ('Brookweed'),
                              ('Buffalo Berry'),
                              ('Buffalo Grass'),
                              ('Bulbous Buttercup'),
                              ('Bull Thistle'),
                              ('Bunchberry'),
                              ('Bur Oak'),
                              ('Burdock'),
                              ('Burnet'),
                              ('Burning Bush'),
                              ('Bush Clover'),
                              ('Bush Honeysuckle'),
                              ('Bush Morning Glory'),
                              ('Butterfly Weed'),
                              ('Buttonwood'),
                              ('Blue Star'),
                              ('Blazing Star'),
                              ('Blue Lily'),
                              ('Blue Ginseng'),
                              ('Blue Jade Vine'),
                              ('Blue Poppy'),
                              ('Blue Wild Indigo'),
                              ('Blue Hibiscus'),
                              ('Blue Mistflower'),
                              ('Blue Sage'),
                              ('Blue Wattle'),
                              ('Blue Vervain'),
                              ('Blue Hyssop'),
                              ('Blue Eyed Grass'),
                              ('Blue Thimbleflower'),
                              ('Blue Phlox'),
                              ('Blue Daisy'),
                              ('Blue Marguerite'),
                              ('Blue Lobelia'),
                              ('Blue Lovegrass'),
                              ('Blue Fescue Grass'),
                              ('Blue Stem Grass'),
                              ('Blue Flame Grass'),
                              ('Blue Tansy'),
                              ('Blue Bell Creeper'),
                              ('Blue Crown Passionflower'),
                              ('Blue Pea Vine'),
                              ('Blue Meadow Cranesbill'),
                              ('Blue Anise Sage'),
                              ('Blue Flag Iris'),
                              --  C
                              ('Cactus'),
                              ('Cabbage'),
                              ('Camellia'),
                              ('Canary Grass'),
                              ('Candytuft'),
                              ('Carnation'),
                              ('Carrot'),
                              ('Castor Bean'),
                              ('Catnip'),
                              ('Cedar'),
                              ('Celery'),
                              ('Century Plant'),
                              ('Chamomile'),
                              ('Cherry Tree'),
                              ('Chestnut Tree'),
                              ('Chicory'),
                              ('Chinese Lantern'),
                              ('Chives'),
                              ('Chrysanthemum'),
                              ('Clematis'),
                              ('Clove'),
                              ('Clover'),
                              ('Coconut Palm'),
                              ('Coffee Plant'),
                              ('Coleus'),
                              ('Columbine'),
                              ('Comfrey'),
                              ('Coneflower'),
                              ('Coral Bells'),
                              ('Corn'),
                              ('Cornflower'),
                              ('Coriander'),
                              ('Cowslip'),
                              ('Cranberry'),
                              ('Creeping Jenny'),
                              ('Cress'),
                              ('Crocosmia'),
                              ('Crocus'),
                              ('Cucumber'),
                              ('Cypress'),

                              --  D
                              ('Daffodil'),
                              ('Dahlia'),
                              ('Daisy'),
                              ('Dandelion'),
                              ('Daphne'),
                              ('Daylily'),
                              ('Dead Nettle'),
                              ('Delphinium'),
                              ('Desert Rose'),
                              ('Devils Ivy'),
                                ('Dogwood'),
                                ('Dragon Tree'),
                                ('Dwarf Iris'),
                                ('Dutchmans Breeches'),

                              -- E
                              ('Echeveria'),
                              ('Elderberry'),
                              ('Elephant Ear'),
                              ('Elm Tree'),
                              ('English Ivy'),
                              ('Eryngium'),
                              ('Eucalyptus'),
                              ('Evening Primrose'),
                              ('Evergreen'),
                              ('Eyebright'),

                              --  F
                              ('Fennel'),
                              ('Fern'),
                              ('Fescue'),
                              ('Fig Tree'),
                              ('Firethorn'),
                              ('Flamingo Flower'),
                              ('Flax'),
                              ('Forget-me-not'),
                              ('Forsythia'),
                              ('Foxglove'),
                              ('Freesia'),
                              ('Fringe Tree'),
                              ('Fuchsia'),

                              --  G
                              ('Gardenia'),
                              ('Garlic'),
                              ('Gentian'),
                              ('Geranium'),
                              ('Ginger'),
                              ('Gladiolus'),
                              ('Gloxinia'),
                              ('Goldenrod'),
                              ('Gooseberry'),
                              ('Gourd'),
                              ('Grape'),
                              ('Grass'),
                              ('Green Bean'),
                              ('Grevillea'),
                              ('Guava'),

                              --  H
                              ('Hackberry'),
                              ('Hawthorn'),
                              ('Hazelnut'),
                              ('Heather'),
                              ('Hebe'),
                              ('Heliotrope'),
                              ('Hellebore'),
                              ('Hemlock'),
                              ('Hemp'),
                              ('Hibiscus'),
                              ('Hickory'),
                              ('Holly'),
                              ('Honeysuckle'),
                              ('Hornbeam'),
                              ('Hosta'),
                              ('Hyacinth'),
                              ('Hydrangea'),
                              ('Hypericum'),
                              -- Rośliny na I
                              ('Ice Plant'),
                              ('Indian Paintbrush'),
                              ('Indian Pipe'),
                              ('Indian Rosewood'),
                              ('Indian Shot'),
                              ('Inkberry'),
                              ('Iris'),
                              ('Ironweed'),
                              ('Italian Arum'),

                              -- Rośliny na J
                              ('Jackfruit'),
                              ('Jacobs Ladder'),
    ('Jade Plant'),
    ('Japanese Maple'),
    ('Japanese Yew'),
    ('Jasmine'),
    ('Jewelweed'),
    ('Jimsonweed'),

    -- Rośliny na K
    ('Kale'),
    ('Kangaroo Paw'),
    ('Kapok Tree'),
    ('Kauri'),
    ('Kelp'),
    ('Kenaf'),
    ('Knapweed'),
    ('Knotweed'),
    ('Koelreuteria'),

    -- Rośliny na L
    ('Ladys Mantle'),
                              ('Lambs Ear'),
    ('Lantana'),
    ('Larch'),
    ('Lavender'),
    ('Leek'),
    ('Lemon Balm'),
    ('Lemon Grass'),
    ('Lemon Tree'),
    ('Lettuce'),
    ('Licorice'),
    ('Lilac'),
    ('Lily'),
    ('Lily of the Valley'),
    ('Linden Tree'),
    ('Lions Tail'),
                              ('Lions Ear'),
    ('Lipstick Plant'),
    ('Liverwort'),
    ('Lobelia'),

    -- Rośliny na M
    ('Magnolia'),
    ('Mahogany'),
    ('Maidenhair Fern'),
    ('Mallow'),
    ('Mandrake'),
    ('Mango Tree'),
    ('Maple Tree'),
    ('Marigold'),
    ('Marjoram'),
    ('Marula'),
    ('Mayapple'),
    ('Meadow Rue'),
    ('Meadow Sage'),
    ('Meadowsweet'),
    ('Milk Thistle'),
    ('Milkweed'),
    ('Mint'),
    ('Mistletoe'),
    ('Mock Orange'),
    ('Monkey Flower'),
    ('Monkshood'),
    ('Morning Glory'),
    ('Mountain Ash'),
    ('Mountain Laurel'),

    -- Rośliny na N
    ('Narcissus'),
    ('Nasturtium'),
    ('Neem Tree'),
    ('Nerine'),
    ('Nettle'),
    ('New Zealand Flax'),
    ('Nightshade'),
    ('Ninebark'),
    ('Nutmeg'),
    ('Nymphaea');

-- Rośliny na O
('Oak'),
    ('Oat'),
    ('Obedient Plant'),
    ('Ocotillo'),
    ('Olive Tree'),
    ('Onion'),
    ('Orange Tree'),
    ('Orchid'),
    ('Oregano'),
    ('Orobanche'),

    -- Rośliny na P
    ('Palm'),
    ('Pansy'),
    ('Papaya'),
    ('Paprika'),
    ('Parsley'),
    ('Parsnip'),
    ('Passionflower'),
    ('Peach Tree'),
    ('Peanut'),
    ('Pear Tree'),
    ('Peas'),
    ('Pecan Tree'),
    ('Pelargonium'),
    ('Pepper'),
    ('Periwinkle'),
    ('Persimmon'),
    ('Petunia'),
    ('Pine Tree'),
    ('Pineapple'),
    ('Plum Tree'),
    ('Poppy'),
    ('Primrose'),
    ('Pumpkin'),

    -- Rośliny na Q
    ('Quaking Aspen'),
    ('Quince'),
    ('Queen Annes Lace'),
    ('Queensland Bottle Tree'),
    ('Quaking Grass'),

    -- Rośliny na R
    ('Radish'),
    ('Ragweed'),
    ('Rainbow Eucalyptus'),
    ('Raspberry'),
    ('Redbud'),
    ('Redwood'),
    ('Rhododendron'),
    ('Rice'),
    ('Rose'),
    ('Rosemary'),
    ('Rue'),

    -- Rośliny na S
    ('Saffron'),
    ('Sage'),
    ('Salvia'),
    ('Sassafras'),
    ('Scabiosa'),
    ('Sea Holly'),
    ('Seaweed'),
    ('Sedum'),
    ('Sesame'),
    ('Shamrock'),
    ('Snapdragon'),
    ('Snowdrop'),
    ('Soybean'),
    ('Spearmint'),
    ('Spirea'),
    ('Spruce'),
    ('Squash'),
    ('Starfruit'),
    ('Strawberry'),
    ('Sugarcane'),
    ('Sunflower'),
    ('Sweet Alyssum'),
    ('Sweet Pea'),
    ('Sweet Potato'),

    -- Rośliny na T
    ('Tamarind'),
    ('Tansy'),
    ('Tarragon'),
    ('Tea Plant'),
    ('Teak'),
    ('Thistle'),
    ('Thyme'),
    ('Tiger Lily'),
    ('Tobacco'),
    ('Tomato'),
    ('Tulip'),
    ('Tulip Tree'),
    ('Tumbleweed'),
    ('Turmeric'),

    -- Rośliny na U
    ('Umbrella Plant'),
    ('Upland Cress'),
    ('Urn Plant'),

    -- Rośliny na V
    ('Vanilla'),
    ('Verbena'),
    ('Vervain'),
    ('Viburnum'),
    ('Vine Maple'),
    ('Violet'),

    -- Rośliny na W
    ('Walnut'),
    ('Watercress'),
    ('Water Hyacinth'),
    ('Water Lily'),
    ('Watermelon'),
    ('Wattle'),
    ('Weeping Willow'),
    ('Wheat'),
    ('White Clover'),
    ('Wild Garlic'),
    ('Wild Ginger'),
    ('Wild Strawberry'),
    ('Winterberry'),

    -- Rośliny na X
    ('Xanadu Philodendron'),
    ('Xanthium'),
    ('Xerophyte'),

    -- Rośliny na Y
    ('Yam'),
    ('Yarrow'),
    ('Yellow Birch'),
    ('Yellowwood'),
    ('Yucca'),

    -- Rośliny na Z
    ('Zebra Grass'),
    ('Zebra Plant'),
    ('Zelkova'),
    ('Zinnia'),
    ('Zucchini');





